import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/page/footer";

// extern imports
import "primeicons/primeicons.css";
import AudioUnlock from "@/components/AudioUnlock";
import InactivityRedirect from "@/components/InactivityRedirect";
import Navbar from "@/components/page/navbar";
import { PerformanceProvider } from "@/context/PerformanceContext";
import { ThemeProvider } from "../context/ThemeContext";
import { KeyboardProvider } from "@/context/KeyboardContext";
import { LogoVisibilityProvider } from "@/context/LogoVisibilityContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Medi-O-Mat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <PerformanceProvider>
        <KeyboardProvider>
          <LogoVisibilityProvider>
            <html lang="en">
              <body className={`${inter.className} bg-bg`}>
                <AudioUnlock />
                <InactivityRedirect />
                <Navbar />
                {children}
                <Footer />
              </body>
            </html>
          </LogoVisibilityProvider>
        </KeyboardProvider>
      </PerformanceProvider>
    </ThemeProvider>
  );
}
