import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/page/footer";

// extern imports
import "primeicons/primeicons.css";
import "animate.css";
import Navbar from "@/components/page/navbar";
import { ThemeProvider } from "../context/ThemeContext";
import { KeyboardProvider } from "@/context/KeyboardContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Medi-O-Mat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <KeyboardProvider>
        <html lang="en">
          <body className={`${inter.className} bg-bg`}>
            <Navbar />
            {children}
            <Footer />
          </body>
        </html>
      </KeyboardProvider>
    </ThemeProvider>
  );
}
