import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/page/footer";

// extern imports
import "primeicons/primeicons.css";
import "animate.css";
import Navbar from "@/components/page/navbar";
import { ThemeProvider } from "../context/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Medi-o-Mat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body className={`${inter.className} bg-bg`}>
          <Navbar />
            {children}
          <Footer />
        </body>
      </html>
    </ThemeProvider>
  );
}
